{
 "title": "Monitor health dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chain",
    "query": {
     "query": "label_values(monitor_contract_latest_head_block{},chain_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RPC request results",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(monitor_rpc_request_results_total{status!=\"ok\"}[20m])",
     "legendFormat": "{{status}} - {{chain_id}} - {{query}}"
    }
   ]
  },
  {
   "title": "Average RPC query durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, increase(monitor_rpc_request_duration_seconds_bucket[5m]))",
     "legendFormat": "{{query}} - {{chain_id}}"
    }
   ]
  },
  {
   "title": "Average DB query duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, increase(monitor_db_query_duration_seconds_bucket[6m]))",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "Syncronization in $chain",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "repeat": "chain",
   "targets": [
    {
     "expr": "{__name__=~\"monitor_contract_latest_head_block|monitor_contract_latest_fetched_block|monitor_contract_latest_processed_block\",chain_id=\"$chain\"} > 0",
     "legendFormat": "{{bridge_id}} - {{__name__}}"
    }
   ]
  }
 ]
}