{
 "title": "XDAI",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "bridge",
    "query": "SELECT DISTINCT bridge_id FROM erc_to_native_messages"
   }
  ]
 },
 "panels": [
  { "title": "Foreign->Home", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total messages",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) as \"Since launch\"\nFROM erc_to_native_messages m\nWHERE m.direction::direction_enum = 'foreign_to_home' AND m.bridge_id = '$bridge';\n"
    },
    {
     "rawSql": "SELECT count(*) as \"Last 7 days\"\nFROM erc_to_native_messages m JOIN sent_messages sm ON sm.bridge_id = m.bridge_id AND sm.msg_hash = m.msg_hash\nJOIN logs l ON l.id = sm.log_id\nJOIN block_timestamps bt ON bt.chain_id = l.chain_id AND bt.block_number = l.block_number\nWHERE m.direction::direction_enum = 'foreign_to_home' AND m.bridge_id = '$bridge' AND now() - bt.timestamp < interval '7 days';\n"
    },
    {
     "rawSql": "SELECT count(*) as \"Last 24 hours\"\nFROM erc_to_native_messages m JOIN sent_messages sm ON sm.bridge_id = m.bridge_id AND sm.msg_hash = m.msg_hash\nJOIN logs l ON l.id = sm.log_id\nJOIN block_timestamps bt ON bt.chain_id = l.chain_id AND bt.block_number = l.block_number\nWHERE m.direction::direction_enum = 'foreign_to_home' AND m.bridge_id = '$bridge' AND now() - bt.timestamp < interval '24 hours';\n"
    }
   ]
  },
  {
   "title": "Messages over time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts.timestamp, '24h'), count(*)\nFROM\n  sent_messages sm\n  JOIN logs l ON l.id = sm.log_id\n  JOIN block_timestamps ts ON ts.chain_id = l.chain_id AND ts.block_number = l.block_number\n  JOIN erc_to_native_messages m ON m.msg_hash = sm.msg_hash AND m.bridge_id = sm.bridge_id\nWHERE m.bridge_id = '$bridge' AND m.direction::text = 'foreign_to_home'\nGROUP BY time\nORDER BY time\n"
    }
   ]
  },
  { "title": "Home->Foreign", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Total messages",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) as \"Since launch\"\nFROM erc_to_native_messages m\nWHERE m.direction::direction_enum = 'home_to_foreign' AND m.bridge_id = '$bridge';\n"
    },
    {
     "rawSql": "SELECT count(*) as \"Last 7 days\"\nFROM erc_to_native_messages m JOIN sent_messages sm ON sm.bridge_id = m.bridge_id AND sm.msg_hash = m.msg_hash\nJOIN logs l ON l.id = sm.log_id\nJOIN block_timestamps bt ON bt.chain_id = l.chain_id AND bt.block_number = l.block_number\nWHERE m.direction::direction_enum = 'home_to_foreign' AND m.bridge_id = '$bridge' AND now() - bt.timestamp < interval '7 days';\n"
    },
    {
     "rawSql": "SELECT count(*) as \"Last 24 hours\"\nFROM erc_to_native_messages m JOIN sent_messages sm ON sm.bridge_id = m.bridge_id AND sm.msg_hash = m.msg_hash\nJOIN logs l ON l.id = sm.log_id\nJOIN block_timestamps bt ON bt.chain_id = l.chain_id AND bt.block_number = l.block_number\nWHERE m.direction::direction_enum = 'home_to_foreign' AND m.bridge_id = '$bridge' AND now() - bt.timestamp < interval '24 hours';\n"
    }
   ]
  },
  {
   "title": "Messages over time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts.timestamp, '24h'), count(*)\nFROM\n  sent_messages sm\n  JOIN logs l ON l.id = sm.log_id\n  JOIN block_timestamps ts ON ts.chain_id = l.chain_id AND ts.block_number = l.block_number\n  JOIN erc_to_native_messages m ON m.msg_hash = sm.msg_hash AND m.bridge_id = sm.bridge_id\nWHERE m.bridge_id = '$bridge' AND m.direction::text = 'home_to_foreign'\nGROUP BY time\nORDER BY time\n"
    }
   ]
  },
  { "title": "Popular message directions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Message stats",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT m.direction, concat('0x', encode(m.receiver, 'hex')) as receiver, sum(m.value) / 1e18 as total, avg(m.value) / 1e18 as average, count(*)\nFROM erc_to_native_messages m\nWHERE m.bridge_id = '$bridge' GROUP BY m.direction, m.receiver\nHAVING count(*) >= 10\nORDER BY count(*) DESC\n"
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Messages waiting for execution",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT bt.\"timestamp\", m.direction, concat('0x', encode(m.receiver, 'hex')) as receiver, m.value / 1e18 as value, concat('0x', encode(l.transaction_hash, 'hex')) as tx_hash\nFROM erc_to_native_messages m JOIN sent_messages sm ON sm.bridge_id = m.bridge_id AND sm.msg_hash = m.msg_hash\nLEFT JOIN executed_messages em ON em.bridge_id = m.bridge_id AND em.message_id = m.msg_hash\nJOIN logs l ON l.id = sm.log_id\nJOIN block_timestamps bt ON bt.chain_id = l.chain_id AND bt.block_number = l.block_number\nWHERE m.bridge_id = '$bridge' AND em.log_id IS NULL AND m.value > 0\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT concat('0x', encode(v.address, 'hex')) as validator, count(v.removed_log_id) < count(*) as enabled,\n(\nSELECT extract(epoch from now() - max(bt.timestamp)) FROM signed_messages s\nJOIN logs l ON s.log_id = l.id\nJOIN block_timestamps bt ON bt.chain_id = l.chain_id AND bt.block_number = l.block_number\nWHERE s.bridge_id = '$bridge' AND s.signer = v.address\n) as since_last_active,\n(\nSELECT count(*) FROM signed_messages s WHERE s.bridge_id = '$bridge' AND s.signer = v.address\n) as total_confirmations\nFROM bridge_validators v\nWHERE v.bridge_id = '$bridge'\nGROUP BY v.address\nORDER BY 2 DESC, 1\n"
    }
   ]
  },
  {
   "title": "Pending validator signatures",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT concat('0x', encode(sm2.signer, 'hex')) as signer, count(*)\nFROM erc_to_native_messages m JOIN sent_messages sm ON sm.bridge_id = m.bridge_id AND sm.msg_hash = m.msg_hash\nJOIN signed_messages sm2 ON sm2.bridge_id = m.bridge_id AND sm2.msg_hash = m.msg_hash\nLEFT JOIN executed_messages em ON em.bridge_id = m.bridge_id AND em.message_id = m.msg_hash\nJOIN logs l ON l.id = sm.log_id\nJOIN block_timestamps bt ON bt.chain_id = l.chain_id AND bt.block_number = l.block_number\nWHERE m.bridge_id = '$bridge' AND m.direction::direction_enum = 'home_to_foreign' AND em.log_id IS NULL\nGROUP BY sm2.signer\n"
    }
   ]
  }
 ]
}